### ISSUE TITLE
运行./import-geoip.sh报错 

### ISSUE THREAD

**Issue by myrshfrs** [crzidea/doh#1]
Ubuntu 24.04.1 LTS (GNU/Linux 6.8.0-41-generic x86_64)
运行`./import-geoip.sh`最后报错

```
jq: parse error: Invalid numeric literal at line 2, column 2
/root/doh/node_modules/wrangler/wrangler-dist/cli.js:29768
            throw a;
            ^

Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:161:15)
    at writeGeneric (node:internal/stream_base_commons:152:3)
    at Socket._writeGeneric (node:net:953:11)
    at Socket._write (node:net:965:8)
    at writeOrBuffer (node:internal/streams/writable:570:12)
    at _write (node:internal/streams/writable:499:10)
    at Writable.write (node:internal/streams/writable:508:10)
    at console.value (node:internal/console/constructor:300:16)
    at console.log (node:internal/console/constructor:383:26)
    at _Logger.doLog (/root/doh/node_modules/wrangler/wrangler-dist/cli.js:152647:28)
Emitted 'error' event on Socket instance at:
    at Socket.onerror (node:internal/streams/readable:1026:14)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:488:12)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}

Node.js v22.8.0
jq: parse error: Invalid numeric literal at line 2, column 2
/root/doh/node_modules/wrangler/wrangler-dist/cli.js:29768
            throw a;
            ^

Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:161:15)
    at writeGeneric (node:internal/stream_base_commons:152:3)
    at Socket._writeGeneric (node:net:953:11)
    at Socket._write (node:net:965:8)
    at writeOrBuffer (node:internal/streams/writable:570:12)
    at _write (node:internal/streams/writable:499:10)
    at Writable.write (node:internal/streams/writable:508:10)
    at console.value (node:internal/console/constructor:300:16)
    at console.log (node:internal/console/constructor:383:26)
    at _Logger.doLog (/root/doh/node_modules/wrangler/wrangler-dist/cli.js:152647:28)
Emitted 'error' event on Socket instance at:
    at Socket.onerror (node:internal/streams/readable:1026:14)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:488:12)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}

Node.js v22.8.0

```

**Comment by crzidea** [comment]
这个是因为 wrangler 由于网络原因报错了，需要先解决与 cloudflare 之间的访问问题。也可以 fork 这个仓库之后用 GitHub Actions 进行部署，这样一般不会有网络问题。

**Comment by myrshfrs** [comment]
是我cloudflare api权限给的不对
